admin_skin_url: https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/admin/front.png
player_skin_url_woman:
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/1.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/2.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/3.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/4.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/5.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/6.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/7.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/8.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/9.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/10.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/11.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/12.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/13.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/14.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/15.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/16.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/17.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/18.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/19.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/20.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/21.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/22.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/23.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/24.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/25.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/26.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/27.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/28.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/29.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/30.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/31.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/32.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/33.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/34.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/35.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/36.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/37.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/38.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/39.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/40.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/41.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/42.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/women/43.png
player_skin_url_man:
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/1.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/2.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/3.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/4.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/5.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/6.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/7.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/8.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/9.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/10.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/11.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/12.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/13.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/14.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/15.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/16.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/17.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/18.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/19.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/20.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/21.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/22.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/23.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/24.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/25.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/26.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/27.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/28.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/29.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/30.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/31.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/32.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/33.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/34.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/35.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/36.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/37.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/38.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/39.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/40.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/41.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/42.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/43.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/44.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/45.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/46.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/47.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/48.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/49.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/50.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/51.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/52.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/53.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/54.png
  - https://raw.githubusercontent.com/singlerr/Skins/refs/heads/master/men/55.png